CREATE TABLE APP.USERS (USER_ID BIGINT NOT NULL, OPENID_USERNAME VARCHAR(1000) NOT NULL, PRIMARY KEY (USER_ID));

ALTER TABLE APP.USERS ADD CONSTRAINT UNQ_USERS_1 UNIQUE (OPENID_USERNAME);

CREATE SEQUENCE APP.USER_ID_SEQUENCE START WITH 1;