CREATE TABLE APP.PROCESSES (PROCESS_ID BIGINT NOT NULL, CONFIGURATION CLOB, INSTALLATION_DATE DATE NOT NULL, PROCESS_EPR VARCHAR(1000), PROCESS_NAME VARCHAR(1000), PROCESS_STATUS INTEGER NOT NULL, PROCESS_TYPE INTEGER NOT NULL, USER_ID BIGINT NOT NULL, INSTRUMENTED_PROCESS_BUNDLE_ID BIGINT, ORIGINAL_PROCESS_BUNDLE_ID BIGINT NOT NULL, PRIMARY KEY (PROCESS_ID));

ALTER TABLE APP.PROCESSES ADD CONSTRAINT UNQ_PROCESSES_3 UNIQUE (PROCESS_EPR);

ALTER TABLE APP.PROCESSES ADD CONSTRAINT FK_PROCESSES_USER_ID FOREIGN KEY (USER_ID) REFERENCES APP.USERS (USER_ID);

CREATE SEQUENCE APP.PROCESS_ID_SEQUENCE START WITH 1;
