ALTER TABLE APP.PROCESSES ADD CONSTRAINT FK_PROCESSES_INSTRUMENTED_PROCESS_BUNDLE_ID FOREIGN KEY (INSTRUMENTED_PROCESS_BUNDLE_ID) REFERENCES APP.PROCESS_BUNDLES (PROCESS_BUNDLE_ID);

ALTER TABLE APP.PROCESSES ADD CONSTRAINT FK_PROCESSES_ORIGINAL_PROCESS_BUNDLE_ID FOREIGN KEY (ORIGINAL_PROCESS_BUNDLE_ID) REFERENCES APP.PROCESS_BUNDLES (PROCESS_BUNDLE_ID);
