CREATE TABLE APP.PROCESS_INSTANCES (PROCESS_INSTANCE_ID BIGINT NOT NULL, END_TIME DATE, ERROR_MESSAGE VARCHAR(1000), PROCESS_INSTANCE_STATE VARCHAR(100) NOT NULL, START_TIME DATE, PROCESS_ID BIGINT NOT NULL, PRIMARY KEY (PROCESS_INSTANCE_ID));

ALTER TABLE APP.PROCESS_INSTANCES ADD CONSTRAINT FK_PROCESS_INSTANCES_PROCESS_ID FOREIGN KEY (PROCESS_ID) REFERENCES APP.PROCESSES (PROCESS_ID);

CREATE SEQUENCE APP.PROCESS_INSTANCE_ID_SEQUENCE START WITH 1;

CREATE INDEX APP.PROCESS_INSTANCES_INDEX1 ON APP.PROCESS_INSTANCES (PROCESS_INSTANCE_STATE);

CREATE INDEX APP.PROCESS_INSTANCES_INDEX2 ON PROCESS_INSTANCES (PROCESS_ID);
