CREATE TABLE APP.TRACES (TRACE_ID BIGINT NOT NULL, EPR VARCHAR(1000) NOT NULL, END_TIME DATE NOT NULL, "INPUT" VARCHAR(20), INVOCATION_STEP VARCHAR(100) NOT NULL, MEP VARCHAR(10) NOT NULL, "OUTPUT" VARCHAR(20), PARTNER VARCHAR(200) NOT NULL, SEQUENCE_NUMBER NUMERIC(22) NOT NULL, "SERVICE" VARCHAR(200) NOT NULL, START_TIME DATE NOT NULL, PROCESS_INSTANCE_ID BIGINT NOT NULL, PRIMARY KEY (TRACE_ID));

ALTER TABLE APP.TRACES ADD CONSTRAINT FK_TRACES_PROCESS_INSTANCE_ID FOREIGN KEY (PROCESS_INSTANCE_ID) REFERENCES APP.PROCESS_INSTANCES (PROCESS_INSTANCE_ID);

CREATE INDEX TRACES_INDEX1 ON APP.TRACES (PROCESS_INSTANCE_ID);

CREATE SEQUENCE APP.TRACE_ID_SEQUENCE START WITH 1;
