DROP TABLE APP.SCORES;
DROP TABLE APP.TRACES;
DROP TABLE APP.PROCESS_INSTANCES;
DROP TABLE APP.PROCESSES;
DROP TABLE APP.PROCESS_BUNDLES;
DROP TABLE APP.USERS;

DROP SEQUENCE APP.USER_ID_SEQUENCE RESTRICT;
DROP SEQUENCE APP.PROCESS_ID_SEQUENCE RESTRICT; 
DROP SEQUENCE APP.PROCESS_BUNDLE_ID_SEQUENCE RESTRICT;
DROP SEQUENCE APP.PROCESS_INSTANCE_ID_SEQUENCE RESTRICT;
DROP SEQUENCE APP.TRACE_ID_SEQUENCE RESTRICT;
DROP SEQUENCE APP.SCORE_ID_SEQUENCE RESTRICT;
