CREATE TABLE USERS 
(
  USER_ID INTEGER NOT NULL 
, OPENID_USERNAME VARCHAR2(1000) NOT NULL 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);

ALTER TABLE USERS
ADD CONSTRAINT USERS_UK1 UNIQUE 
(
  OPENID_USERNAME 
)
ENABLE;

CREATE SEQUENCE USER_ID_SEQUENCE INCREMENT BY 1 START WITH 1 CACHE 20;
