CREATE TABLE PROCESS_BUNDLES 
(
  PROCESS_BUNDLE_ID INTEGER NOT NULL 
, CONTENTS BLOB NOT NULL 
, CONSTRAINT PROCESS_BUNDLE_PK PRIMARY KEY 
  (
    PROCESS_BUNDLE_ID 
  )
  ENABLE 
);

CREATE SEQUENCE PROCESS_BUNDLE_ID_SEQUENCE INCREMENT BY 1 START WITH 1 CACHE 20;
