CREATE TABLE PROCESS_INSTANCES 
(
  PROCESS_INSTANCE_ID INTEGER NOT NULL 
, PROCESS_ID INTEGER NOT NULL 
, PROCESS_INSTANCE_STATE VARCHAR2(100) NOT NULL 
, START_TIME DATE 
, END_TIME DATE 
, ERROR_MESSAGE VARCHAR2(1000) 
, CONSTRAINT PROCESS_INSTANCE_PK PRIMARY KEY 
  (
    PROCESS_INSTANCE_ID 
  )
  ENABLE 
);

ALTER TABLE PROCESS_INSTANCES
ADD CONSTRAINT PROCESS_INSTANCE_PROCESSE_FK1 FOREIGN KEY
(
  PROCESS_ID 
)
REFERENCES PROCESSES
(
  PROCESS_ID 
)
ENABLE;

CREATE INDEX PROCESS_INSTANCES_INDEX1 ON PROCESS_INSTANCES (PROCESS_INSTANCE_STATE);

CREATE INDEX PROCESS_INSTANCES_INDEX2 ON PROCESS_INSTANCES (PROCESS_ID);

CREATE SEQUENCE PROCESS_INSTANCE_ID_SEQUENCE INCREMENT BY 1 START WITH 1 CACHE 20;
