CREATE TABLE TRACES 
(
  TRACE_ID INTEGER NOT NULL 
, EPR VARCHAR2(1000) NOT NULL 
, PARTNER VARCHAR2(200) NOT NULL 
, SERVICE VARCHAR2(200) NOT NULL 
, MEP VARCHAR2(10) NOT NULL 
, INVOCATION_STEP VARCHAR2(100) NOT NULL 
, SEQUENCE_NUMBER INT NOT NULL 
, START_TIME DATE NOT NULL 
, END_TIME DATE NOT NULL 
, INPUT VARCHAR2(20) 
, OUTPUT VARCHAR2(20) 
, PROCESS_INSTANCE_ID INTEGER NOT NULL 
, CONSTRAINT TRACES_PK PRIMARY KEY 
  (
    TRACE_ID 
  )
  ENABLE 
);

ALTER TABLE TRACES
ADD CONSTRAINT TRACES_PROCESS_INSTANCES_FK1 FOREIGN KEY
(
  PROCESS_INSTANCE_ID 
)
REFERENCES PROCESS_INSTANCES
(
  PROCESS_INSTANCE_ID 
)
ENABLE;

CREATE INDEX TRACES_INDEX1 ON TRACES (PROCESS_INSTANCE_ID);

CREATE SEQUENCE TRACE_ID_SEQUENCE INCREMENT BY 1 START WITH 1 CACHE 20;
